---
install_mode: debian
elasticsearch_api_port: 9200

elasticsearch_service_dropin_template: "{{ playbook_dir }}/templates/elasticsearch/service.conf"

elasticsearch_config:
  node.name: "{{ elasticsearch_api_host }}"
  cluster.name: idealista-cluster
  network.host: _site_
  discovery.seed_hosts: ["esmasterdata1", "esmasterdata2", "esmasterdata3"]
  cluster.initial_master_nodes: ["esmasterdata1", "esmasterdata2", "esmasterdata3"]
  http.port: "{{ elasticsearch_api_port }}"
  bootstrap.memory_lock: true
  node.data: true
  node.master: true
  node.ingest: false

elasticsearch_jvm_custom_parameters:
  - '-Xms256m'
  - '-Xmx256m'
  - '-Des.transport.cname_in_publish_address=true'

elasticsearch_os_tuning: false

elasticsearch_plugins:
  - name: mapper-size
    state: present
