---
language: python
python: "3.7"
os: linux
services:
  - docker
install:
  - pip install pipenv
  - pipenv sync
  - sudo sysctl -w vm.max_map_count=262144
script:
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
