---

- name: Elasticsearch | Install
  import_tasks: install.yml
  tags:
    - elasticsearch_install

- name: Elasticsearch | Configure
  import_tasks: config.yml
  tags:
    - elasticsearch_configure

- name: Elasticsearch | Plugins
  import_tasks: plugins.yml
  tags:
    - elasticsearch_plugins

- name: Elasticsearch | Service
  import_tasks: service.yml
  tags:
    - elasticsearch_service
