---

elasticsearch_api_port: 9200
elasticsearch_tcp_port: 9300

elasticsearch_config:
  node.name: "{{ elasticsearch_api_host }}"
  cluster.name: idealista-cluster
  network.host: _site_
  discovery.zen.ping.unicast.hosts: ["esmasterdata1", "esmasterdata2", "esmasterdata3"]
  discovery.zen.minimum_master_nodes: 2
  http.port: "{{ elasticsearch_api_port }}"
  transport.tcp.port: "{{ elasticsearch_tcp_port }}"
  bootstrap.memory_lock: true
  node.data: true
  node.master: true
  node.ingest: false
  node.ml: false
  cluster.remote.connect: false
  http.cors.enabled: true
  http.cors.allow-origin: "*"
  xpack.security.enabled: false
  xpack.monitoring.enabled: false
  xpack.watcher.enabled: false
  xpack.ml.enabled: false
