---

- name: restart elasticsearch
  systemd:
    name: elasticsearch
    state: restarted
    daemon_reload: true
  when: elasticsearch_service_state != 'stopped' and elasticsearch_service_output.changed == False
