---

- name: Elasticsearch | Add gpg key
  apt_key:
    url: "{{ opendistro_gpg_key }}"
    state: present

- name: Elasticsearch | Add ppa repository
  apt_repository:
    repo: "{{ opendistro_ppa_source }}"
    state: present
    filename: elasticsearch_opendistro

- name: Elasticsearch | Gather package facts
  package_facts:
    manager: "auto"

- name: Elasticsearch | Install elasticsearch_opendistro {{ opendistro_version }}
  apt:
    name: "opendistroforelasticsearch={{ opendistro_version }}-1"
    update_cache: true
    state: "{{ opendistro_package_state }}"
    force: "{{ (opendistro_version not in ansible_facts.packages[item][0].version) | ternary(True, omit) }}"
  notify: restart elasticsearch
